services:
  redpanda:
    image: redpandadata/redpanda:v23.3.6
    command:
      - redpanda start
      - --smp 1
      - --memory 512M
      - --overprovisioned
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    expose:
      - "9092"
      - "29092"
    restart: unless-stopped
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: crypto_db
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: crypto_pass
    expose:
      - "5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: unless-stopped
  producer:
    build: ./producer
    depends_on:
      - redpanda
    environment:
      BOOTSTRAP_SERVERS: redpanda:29092
      TOPIC_NAME: crypto-prices
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped
  consumer:
    build: ./consumer
    depends_on:
      - redpanda
      - postgres
    environment:
      BOOTSTRAP_SERVERS: redpanda:29092
      TOPIC_NAME: crypto-prices
      DB_HOST: postgres
      DB_NAME: crypto_db
      DB_USER: crypto_user
      DB_PASSWORD: crypto_pass
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped
  dbt:
    build: ./dbt_crypto
    depends_on:
      - postgres
    environment:
      PYTHONUNBUFFERED: "1"
    profiles:
      - dbt
  airflow-init:
    build: ./airflow
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username admin --password admin --firstname Kelash --lastname Kumar --role Admin --email kelash@admin.com"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://crypto_user:crypto_pass@postgres:5432/crypto_db
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    depends_on:
      - postgres
  airflow-webserver:
    build: ./airflow
    command: airflow webserver --port 8080
    expose:
      - "8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://crypto_user:crypto_pass@postgres:5432/crypto_db
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      PYTHONUNBUFFERED: "1"
    depends_on:
      - postgres
      - airflow-init
    restart: unless-stopped
  airflow-scheduler:
    build: ./airflow
    command: airflow scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://crypto_user:crypto_pass@postgres:5432/crypto_db
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      PYTHONUNBUFFERED: "1"
    depends_on:
      - postgres
      - airflow-init
    restart: unless-stopped
  metabase:
    image: metabase/metabase:v0.60.2.5
    expose:
      - "3000"
    depends_on:
      - postgres
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: postgres
      MB_DB_PORT: 5432
      MB_DB_DBNAME: metabase_db
      MB_DB_USER: metabase_user
      MB_DB_PASS: metabase_pass
    restart: unless-stopped
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - metabase
    restart: unless-stopped
volumes:
  pg-data:
  caddy_data:
  caddy_config:
